/**
 * Validates whether a lap looks like a lap or whether it's full of junk.
 * @module src/validation/run
 */

const common = require('./common.js');
const log = require('../utils/logger.js').getLogger();


/**
 * Parses a request with lap data to see whether that data is valid or not.
 * @param {Request} req - A request generated by express router
 * @return {Promise}
 * resolve returns parsed and validated data as a {@link module:public/types~lap|lap}.<br>
 * reject if the validation failed somehow.
 */
function parseRequest(req) {
    console.log(req.body);
    const dataType = req.path.slice(1);
    switch (dataType) {
        case 'lap':
            return parseLapData(
                req.body.id,
                req.body.unit,
                req.body.distance,
                req.body.time);
        case 'activity':
            return parseActivityData(
                req.body.id,
                req.body.activity,
                req.body.kit,
                req.body.weather,
                req.body.temp,
                req.body.effort);
        default:
            return null;
    }
};


/**
 * Parses a request with lap data to see whether that data is valid or not.
 * @param {string} id - An id for this lap
 * @param {string} unit - The measurement used for this lap
 * @param {string} distance - The distance covered in this lap
 * @param {string} time - The time taken to covere this lap
 * @return {Promise}
 * resolve returns parsed and validated data as a {@link module:public/types~lap|lap}.<br>
 * reject if the validation failed somehow.
 */
function parseLapData(id, unit, distance, time) {
    log.debug('Parsing lap id:[%s] unit:[%s] distance:[%s] time:[%s]', id, unit, distance, time);
    return new Promise((resolve, reject) => {
        if (isValidLap(id, unit, distance, time)) {
            let payload = {
                id: id,
                unit: unit,
                distance: distance,
                time: time,
            };
            resolve(payload);
        } else {
            reject('bad');
        }
    });
};


/**
 * Parses a request with activity data to see whether that data is valid or not.
 * @param {number} id - Activity id
 * @param {string} activity - The activity the set of Laps will define
 * @param {string} kit - The kit I relied on for this activity
 * @param {string} weather - What was the weather like
 * @param {string} temp - What did the temperature feel like
 * @param {string} effort - And what was the perceived effort
 * @return {Promise}
 * resolve returns parsed and validated data as a {@link module:public/types~lap|lap}.<br>
 * reject if the validation failed somehow.
 */
function parseActivityData(id, activity, kit, weather, temp, effort) {
    log.debug('Parsing activity id:[%s] activity:[%s]kit:[%s] weather:[%s] temp:[%s] effort:[%s]', id, activity, kit, weather, temp, effort);
    return new Promise((resolve, reject) => {
        if (isValidActivity(id, activity, kit, weather, temp, effort)) {
            let payload = {
                id: id,
                activity: activity,
                kit: kit,
                weather: weather,
                temp: temp,
                effort: effort,
            };
            resolve(payload);
        } else {
            reject('bad');
        }
    });
};


function isValidLap(id, unit, distance, time) {
    return (isValidDistance(distance) &&
        isValidTime24(time));
};


function isValidActivity(id, unit, distance, time) {
    return true;
};


function isValidDistance(dist) {
    return (typeof (dist) != 'undefined' &&
        common.isFloatExpr(dist) &&
        dist > 0);
};


function isValidTime24(time) {
    return (typeof (time) != 'undefined' &&
        common.isTimeExpr24(time));
};


module.exports = {
    parseRequest: parseRequest,
    parseLapData: parseLapData,
};
